export const BAND_RANGES: { band: string; min_khz: number; max_khz: number }[] = [
  { band: '120m', min_khz: 2300, max_khz: 2495 },
  { band: '90m', min_khz: 3200, max_khz: 3400 },
  { band: '75m', min_khz: 3900, max_khz: 4000 },
  { band: '60m', min_khz: 4750, max_khz: 5060 },
  { band: '49m', min_khz: 5900, max_khz: 6200 },
  { band: '41m', min_khz: 7200, max_khz: 7450 },
  { band: '31m', min_khz: 9400, max_khz: 9900 },
  { band: '25m', min_khz: 11600, max_khz: 12100 },
  { band: '22m', min_khz: 13570, max_khz: 13870 },
  { band: '19m', min_khz: 15100, max_khz: 15800 },
  { band: '16m', min_khz: 17480, max_khz: 17900 },
  { band: '15m', min_khz: 18900, max_khz: 19020 },
  { band: '13m', min_khz: 21450, max_khz: 21850 },
  { band: '11m', min_khz: 25600, max_khz: 26100 },
];

export const LANGUAGE_CODES: Record<string, string> = {
  '-CW': 'Morse Code',
  '-MX': 'Music',
  '-TS': 'Time Signal',
  A: 'Arabic',
  Ab: 'Abkhaz',
  Ac: 'Aceh',
  Ad: 'Adyghe',
  Af: 'Afrikaans',
  Ak: 'Akan',
  Al: 'Albanian',
  Am: 'Amharic',
  Ar: 'Armenian',
  As: 'Assamese',
  Av: 'Avar',
  Ay: 'Aymara',
  Az: 'Azerbaijani',
  Ba: 'Bashkir',
  Bd: 'Bodo',
  Be: 'Belarusian',
  Bg: 'Bulgarian',
  Bh: 'Bhili',
  Bi: 'Bislama',
  Bj: 'Bemba',
  Bm: 'Bambara',
  Bn: 'Bengali',
  Bo: 'Tibetan',
  Br: 'Breton',
  Bs: 'Bosnian',
  Bu: 'Burmese',
  C: 'Chinese',
  Ca: 'Cantonese',
  Cb: 'Chabo',
  Cc: 'Chaochow',
  Ce: 'Chechen',
  Ch: 'Chin',
  Ck: 'Chakma',
  Cm: 'Cham',
  Co: 'Corsican',
  Cr: 'Croatian',
  Ct: 'Catalan',
  Cv: 'Chuvash',
  Cz: 'Czech',
  D: 'German',
  Da: 'Danish',
  Dg: 'Dogri',
  Dh: 'Dhivehi',
  Di: 'Dinka',
  Dk: 'Dakhla',
  Do: 'Dogrib',
  Dr: 'Dari',
  Ds: 'Dayak',
  Dz: 'Dzongkha',
  E: 'English',
  Ea: 'Shan',
  Ec: 'Eastern Cham',
  Ed: 'Ende',
  Ew: 'Ewe',
  F: 'French',
  Fa: 'Faroese',
  Fi: 'Finnish',
  Fj: 'Fijian',
  Fl: 'Filipino',
  Fo: 'Fon',
  Fu: 'Fulfulde',
  G: 'German',
  Ga: 'Ga',
  Ge: 'Georgian',
  Gj: 'Gujarati',
  Gk: 'Greek',
  Gl: 'Galician',
  Go: 'Gorontalo',
  Gn: 'Guarani',
  Gu: 'Gurenne',
  H: 'Hindi',
  Ha: 'Hausa',
  Hb: 'Hebrew',
  Hk: 'Hakka',
  Hm: 'Hmong',
  Hr: 'Croatian',
  Ht: 'Hattian',
  Hu: 'Hungarian',
  Hy: 'Armenian',
  I: 'Italian',
  Ic: 'Icelandic',
  Id: 'Indonesian',
  Ig: 'Igbo',
  In: 'Indonesian',
  Ir: 'Irish',
  J: 'Japanese',
  Jv: 'Javanese',
  K: 'Korean',
  Ka: 'Karen',
  Kb: 'Kabyle',
  Kc: 'Kachin',
  Kd: 'Kannada',
  Kg: 'Kyrgyz',
  Kh: 'Khmer',
  Ki: 'Kikuyu',
  Kk: 'Kazakh',
  Km: 'Khmer',
  Kn: 'Kannada',
  Ko: 'Korean',
  Kr: 'Karen',
  Ku: 'Kurdish',
  Kz: 'Kazakh',
  L: 'Latin',
  La: 'Lao',
  Lb: 'Lamba',
  Li: 'Lingala',
  Ln: 'Lingala',
  Lo: 'Lozi',
  Lt: 'Lithuanian',
  Lu: 'Lunda',
  Lv: 'Latvian',
  M: 'Mandarin',
  Ma: 'Malay',
  Mc: 'Macedonian',
  Mg: 'Malagasy',
  Mi: 'Minangkabau',
  Mk: 'Macedonian',
  Ml: 'Malayalam',
  Mn: 'Mongolian',
  Mo: 'Moldovan',
  Mr: 'Marathi',
  Ms: 'Malay',
  Mt: 'Maltese',
  My: 'Burmese',
  N: 'Dutch',
  Nb: 'Norwegian',
  Ne: 'Nepali',
  Ng: 'Nguni',
  Ni: 'Niuean',
  Nl: 'Dutch',
  No: 'Norwegian',
  Np: 'Nepali',
  Nw: 'Newari',
  Ny: 'Nyanja',
  O: 'Oriya',
  Om: 'Oromo',
  Or: 'Oriya',
  Os: 'Ossetian',
  P: 'Portuguese',
  Pa: 'Pashto',
  Pj: 'Punjabi',
  Pl: 'Polish',
  Ps: 'Pashto',
  Q: 'Quechua',
  R: 'Russian',
  Rm: 'Romanian',
  Rn: 'Rundi',
  Ro: 'Romanian',
  Rs: 'Russian',
  Rw: 'Kinyarwanda',
  S: 'Spanish',
  Sa: 'Sango',
  Sb: 'Serbian',
  Sc: 'Sichuan Yi',
  Sd: 'Sindhi',
  Se: 'Sena',
  Sg: 'Shangaan',
  Sh: 'Serbo-Croatian',
  Si: 'Sinhalese',
  Sk: 'Slovak',
  Sl: 'Slovenian',
  Sm: 'Samoan',
  Sn: 'Shona',
  So: 'Somali',
  Sq: 'Albanian',
  Sr: 'Serbian',
  Su: 'Sundanese',
  Sv: 'Swedish',
  Sw: 'Swahili',
  T: 'Thai',
  Ta: 'Tamil',
  Tb: 'Tibetan',
  Te: 'Telugu',
  Tg: 'Tajik',
  Tk: 'Turkmen',
  Tl: 'Tagalog',
  Tn: 'Tswana',
  To: 'Tongan',
  Tp: 'Tok Pisin',
  Tr: 'Turkish',
  Ts: 'Tsonga',
  Tu: 'Turkish',
  Tv: 'Tuvaluan',
  Tw: 'Twi',
  U: 'Urdu',
  Ug: 'Uighur',
  Uk: 'Ukrainian',
  Ur: 'Urdu',
  Uz: 'Uzbek',
  V: 'Vietnamese',
  Ve: 'Venda',
  Vn: 'Vietnamese',
  W: 'Wolof',
  Wa: 'Walloon',
  Wo: 'Wolof',
  X: 'Xhosa',
  Y: 'Yoruba',
  Yo: 'Yoruba',
  Z: 'Zulu',
  Zh: 'Chinese',
  Zu: 'Zulu',
};

export const TARGET_AREAS: Record<string, string> = {
  Af: 'Africa',
  Am: 'Americas',
  As: 'Asia',
  CAf: 'Central Africa',
  CAm: 'Central America',
  CAs: 'Central Asia',
  Car: 'Caribbean',
  EAf: 'East Africa',
  EAs: 'East Asia',
  EEu: 'Eastern Europe',
  ENAm: 'Eastern North America',
  Eu: 'Europe',
  FE: 'Far East',
  LAm: 'Latin America',
  ME: 'Middle East',
  NAf: 'North Africa',
  NAm: 'North America',
  NEu: 'Northern Europe',
  Oc: 'Oceania',
  Pac: 'Pacific',
  SAf: 'Southern Africa',
  SAm: 'South America',
  SAs: 'South Asia',
  SEAs: 'South East Asia',
  SEu: 'Southern Europe',
  WAf: 'West Africa',
  WEu: 'Western Europe',
  WNAm: 'Western North America',
};

export function getBand(freq_khz: number): string {
  for (const range of BAND_RANGES) {
    if (freq_khz >= range.min_khz && freq_khz <= range.max_khz) {
      return range.band;
    }
  }
  return 'OOB';
}

export function getLanguageName(code: string): string {
  return LANGUAGE_CODES[code] || code;
}

export function getTargetName(code: string): string {
  return TARGET_AREAS[code] || code;
}
